### ISSUE TITLE
ワークフロー定義の.clinerules-pmへの追加

### ISSUE THREAD

**Issue by sakaritoru** [sakaritoru/gemmini-ai-custom-function#9]
## 目的
プロジェクト管理作業で使用するツールと作業フローを.clinerules-pmに定義し、効率的な作業を可能にする

#### GitHub APIツール
- [ ] create_issue
  - 目的：新規issueの作成
  - 用途：タスク管理、機能要望の記録
- [ ] create_branch
  - 目的：機能開発用ブランチの作成
  - 用途：作業用ブランチの分離
- [ ] create_or_update_file
  - 目的：ファイルの作成・更新
  - 用途：設定ファイル、ドキュメントの管理
- [ ] create_pull_request
  - 目的：プルリクエストの作成
  - 用途：コードレビュー、変更の統合

#### Playwrightツール
- [ ] playwright_navigate
  - 目的：ドキュメントページへの移動
  - 用途：APIドキュメントの参照
- [ ] playwright_get_visible_text
  - 目的：ページ内容の取得・確認
  - 用途：ドキュメント内容の解析

### 2. 作業フローの定義
- [ ] ドキュメント参照フロー
  1. playwright_navigateでドキュメントページに移動
  2. playwright_get_visible_textで内容確認
  3. 必要な情報の抽出と活用

- [ ] issue作成フロー
  1. create_issueでissue作成
  2. ラベルや優先度の設定
  3. 関連タスクの追跡

- [ ] コード変更フロー
  1. create_branchで作業ブランチ作成
  2. create_or_update_fileで変更実施
  3. create_pull_requestでレビュー依頼

### 3. .clinerules-pmの更新
```yaml
tools:
  github:
    create_issue:
      purpose: "新規issueの作成、タスク管理"
      usage: "タスク管理、機能要望の記録"
    create_branch:
      purpose: "機能開発用の新規ブランチ作成"
      usage: "作業用ブランチの分離"
    create_or_update_file:
      purpose: "プロジェクト関連ファイルの作成・更新"
      usage: "設定ファイル、ドキュメントの管理"
    create_pull_request:
      purpose: "変更のレビュー依頼、マージ準備"
      usage: "コードレビュー、変更の統合"
  playwright:
    playwright_navigate:
      purpose: "ドキュメントやWebページの参照"
      usage: "APIドキュメントの参照"
    playwright_get_visible_text:
      purpose: "ページ内容の取得・確認"
      usage: "ドキュメント内容の解析"
workflows:
  documentation:
    description: "ドキュメント参照手順"
    steps:
      - navigate_to_docs
      - extract_content
      - analyze_and_use
  issue_management:
    description: "issue作成から管理まで"
    steps:
      - create_new_issue
      - set_metadata
      - track_progress
  code_change:
    description: "コード変更の手順"
    steps:
      - create_feature_branch
      - implement_changes
      - request_review
```

## 受け入れ基準
- [ ] 必要なツールがすべて定義され、その目的と用途が明確に記述されていること
- [ ] 各作業フローが具体的な手順として記述されていること
- [ ] CLINEがツールと作業フローを認識できること
- [ ] 後から参照する際にわかりやすいドキュメントになっていること

## 関連
- #4 PMロールと基本ディレクトリ構造の設定
